export const UPDATE_PERSONAL_DETAILS = "UPDATE_PERSONAL_DETAILS";
export const UPDATE_EDUCATION_DETAILS = "UPDATE_EDUCATION_DETAILS";
export const UPDATE_EXPERIENCE_DETAILS = "UPDATE_EXPERIENCE_DETAILS";

export const SET_STEP = "SET_STEP";
export const NEXT_STEP = "NEXT_STEP";
export const PREV_STEP = "PREV_STEP";
